### ISSUE TITLE
Add an endpoint to fetch a quote by ID

### ISSUE THREAD

**Issue by simonpweller** [simonpweller/quotes-api#10]
An ID property will have to be added to the quotes to support this. 

The new endopint should have the route /{id}

**Comment by dragoFireup** [comment]
Created a [pull request](https://github.com/simonpweller/quotes-api/pull/11) for this issue.

**Comment by simonpweller** [comment]
Thank you for checking out the repo and getting involved! I've given you some feedback on the pull request.

**Comment by dragoFireup** [comment]
Updated the request with changes and requested for a re-review. Please check that.
