### ISSUE TITLE
Shift routes to separate routes file

### ISSUE THREAD

**Issue by simonpweller** [simonpweller/quotes-api#5]
Currently the routes are all in the main app file, which will quickly become cluttered. Let's shift them to a separate file. There's an example of how this can be done in the express documentation:
http://expressjs.com/en/guide/routing.html#express-router

**Comment by Serhazor** [comment]
QQ: Do you need to Routes file or the Routes folder ?

**Comment by simonpweller** [comment]
I think for now just a routes file will do since there's just a couple of them at them moment.

**Comment by simonpweller** [comment]
@Serhazor are you interested in opening a PR for this one?

**Comment by Serhazor** [comment]
I would be interested, yes. I've forked the repo and figuring out how to do it (I am complete newby in it, so bare with me :-))

**Comment by simonpweller** [comment]
No problem at all - take your time and give me a shout if I can help. I've just assigned it to you for now so others can see someone is already working on this.
